---
- name: Ensure Homebrew is installed
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

- name: Add Homebrew to PATH for Ansible run
  ansible.builtin.shell: |
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  args:
    executable: /bin/bash

- name: Install Homebrew packages
  ansible.builtin.command: brew install "{{ item }}"
  loop: "{{ homebrew_packages }}"
